name: sheber_market
description: "sheber_market"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_masked_text: ^3.0.1
  provider: ^6.1.2
  logger: ^2.4.0
  pinput: ^5.0.0
  vibration: ^1.9.0
  uuid: ^4.2.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  google_nav_bar: ^5.0.6
  multi_image_picker_view: ^1.0.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  masked_text_field: ^1.0.2
  collection: ^1.17.2
  lottie: ^3.1.2
  image_picker: ^1.0.8
  credit_card_validator: ^2.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  flutter_cache_manager: ^3.3.2
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_typeahead: ^5.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  firebase_app_check: ^0.3.0+3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Убедитесь, что эта строка присутствует

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/sheber_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/sheber_logo.png
