// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDr_oVBN8OQZNhtNbI2PNbkZ2PJBCnFw',
    appId: '1:264391817850:web:7f044f543a9f3733d959c3',
    messagingSenderId: '264391817850',
    projectId: 'sheber-6fda8',
    authDomain: 'sheber-6fda8.firebaseapp.com',
    storageBucket: 'sheber-6fda8.appspot.com',
    measurementId: 'G-NY7TJSL8LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_3mQvER5Om9kM-TfKzc96cyCnrjLInI',
    appId: '1:264391817850:android:9db246bd6c2bafb7d959c3',
    messagingSenderId: '264391817850',
    projectId: 'sheber-6fda8',
    storageBucket: 'sheber-6fda8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCsFHpxAAnU-YMiYwaXxzryxQpxduMg8',
    appId: '1:264391817850:ios:19f75939c3e9bf7dd959c3',
    messagingSenderId: '264391817850',
    projectId: 'sheber-6fda8',
    storageBucket: 'sheber-6fda8.appspot.com',
    iosBundleId: 'com.dev.sheberMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHCsFHpxAAnU-YMiYwaXxzryxQpxduMg8',
    appId: '1:264391817850:ios:fb14eedd0faa4db6d959c3',
    messagingSenderId: '264391817850',
    projectId: 'sheber-6fda8',
    storageBucket: 'sheber-6fda8.appspot.com',
    iosBundleId: 'com.sheber.dev.sheberMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzDr_oVBN8OQZNhtNbI2PNbkZ2PJBCnFw',
    appId: '1:264391817850:web:826c9173c4cd3d2fd959c3',
    messagingSenderId: '264391817850',
    projectId: 'sheber-6fda8',
    authDomain: 'sheber-6fda8.firebaseapp.com',
    storageBucket: 'sheber-6fda8.appspot.com',
    measurementId: 'G-CFLVKFHSY2',
  );
}
